[package]
name = "coin_alpha"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
dotenv = {version = "0.15.0" }
reqwest = "0.11.4"
